#加密配置
jasypt:
  encryptor:
    password: lengleng
fdfs:
  file-host: http://49.4.12.152:8888/
  tracker-list:
    - 49.4.12.152:22122
server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  cloud: 
    stream: 
      default-binder: kafka
      kafka: 
        binder:
          zk-nodes: 49.4.12.198:2181
          brokers: 49.4.12.198:9092
  redis:
    remote: false        #cachecloud 获取
    host: 49.4.12.13
    port: 6666
    password: moshushi123
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true
    clients: unis-auth,unis-upms-service,unis-project-service,unis-expert-service,unis-search-service
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#分布式事务管理LCN --txmanager事务管理器地址
tm:
  manager: 
    url: http://192.168.1.8:8899/tx/manager/    

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
#自然语言处理配置
nlp:
  root-path: /mss/HanLP
#  root-path: E:/JavaSoft/hanlp
  title-similar-threshold: 0.8
  similar-threshold: 0.85
  keyword-extract-num: 5
  custom-keyword-path: ${nlp.root-path}/data/keyword.txt
  word-vector:
    train-file-name: ${nlp.root-path}/data/test/test.txt
    model-file-name: ${nlp.root-path}/data/model/wordVector/word2vector.txt
  text-classfiy:
    model-file-name: ${nlp.root-path}/data/model/classification/classification-model.ser
