server:
  port: 4060
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: moshushi123
    url: jdbc:mysql://49.4.12.66:3306/unis?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 49.4.12.198:2181
      namespace: unis-daemon
